---
os: linux
dist: xenial
before_install:
  #- "if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then CMAKE_INSTALLER=install-cmake.sh; curl -sSL https://cmake.org/files/v3.18/cmake-3.18.4-Linux-x86_64.sh -o ${CMAKE_INSTALLER}; chmod +x ${CMAKE_INSTALLER}; sudo ./${CMAKE_INSTALLER} --prefix=/usr/local --skip-license; export PATH=/usr/local/bin:${PATH}; fi"
  - "CMAKE_INSTALLER=.travis.dependencies/install-cmake-3.18.4-Linux-x86_64.sh; chmod +x ${CMAKE_INSTALLER}; sudo ${CMAKE_INSTALLER} --prefix=/usr/local --skip-license; export PATH=/usr/local/bin:${PATH}"
  - "sudo apt-get -y install graphviz"
  - "python3 -m pip install --upgrade pip"
install:
  - "pip3 install -r requirements.txt"
  - "python3 setup.py install"
language: python
python: 
  - "3.6"
  - "3.7"
  - "3.8"
script: 
  - "python3 tests/model_evaluation.py"
  - "python3 tests/datasets.py"
  - "python3 tests/kNN.py"
  - "python3 tests/naive_bayes.py"
  - "python3 tests/SVM.py"
  - "python3 tests/decision_tree.py"
  - "python3 tests/neural_network.py"
  - "python3 tests/logistic_regression.py"
  - "python3 tests/linear_regression.py"
  - "python3 tests/DSA.py"
  - "python3 tests/imbalanced_data.py"
  - "python3 tests/decomposition.py"
  - "python3 tests/gradient_descent.py"
  - "python3 tests/ensemble.py"
  - "python3 tests/math_and_stats.py"
  - "python3 tests/pipeline.py"
  - "python3 tests/utils.py"
  - "python3 tests/database.py"
  - "python3 tests/clustering.py"
  - "python3 tests/anomaly_detection.py"
  - "python3 tests/network_analysis.py"
