language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
#  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - ls -latrd
# command to run tests
script:
  - cd tests

